---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  test-deploy
  namespace: default
  labels:
    app:  test-deploy
spec:
  selector:
    matchLabels:
      app: test-deploy
  replicas: 1
  template:
    metadata:
      labels:
        app:  test-deploy
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name:  http
      restartPolicy: Always
